spring.application.name=gatewaybatch5

server.port=8082

eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka

# Producer Service Route
spring.cloud.gateway.routes[0].id=banking
spring.cloud.gateway.routes[0].uri=http://localhost:10000
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/employees/**